#!/usr/bin/env python3
"""
audit_skill.py — run a set of heuristics against a draft skill and flag concerns.

Anti-slop linter. Every flag is a suggestion, not a hard stop — review each one.
The heuristics are based on failure modes I've hit building real skills.

Usage:
    python audit_skill.py /path/to/skill/
    python audit_skill.py /path/to/skill/ --json   # machine-readable output

What it checks:
  1. Frontmatter: present, valid fields, description length
  2. Description triggering: too generic, too short, lacks "pushy" signals
  3. Suspicious numbers: round prices (e.g. $3.50/hr), dates ending in .00
  4. Generic AI-sounding attributions (footers with "Agent", "AI", etc.)
  5. Fabricated-looking identifiers (function names not grep-able in common repos)
  6. Stale "verified" markers (dates >90 days old without confirmation)
  7. Missing ERRATA.md in tier-3-shaped skills
  8. Scripts: Python syntax, docstring presence, __main__ guard
  9. Copy-pasted LLM-slop footers ("Generated by Claude", etc.)
"""

from __future__ import annotations

import argparse
import ast
import json
import re
import sys
from dataclasses import dataclass, field, asdict
from datetime import date, datetime, timedelta
from pathlib import Path


@dataclass
class Finding:
    severity: str  # "info" | "warn" | "flag"
    category: str
    file: str
    line: int | None
    message: str
    suggestion: str = ""


@dataclass
class AuditReport:
    skill_path: str
    findings: list[Finding] = field(default_factory=list)

    def add(self, severity: str, category: str, file: str, line: int | None,
            message: str, suggestion: str = "") -> None:
        self.findings.append(Finding(severity, category, file, line, message, suggestion))

    def by_severity(self) -> dict[str, int]:
        counts = {"flag": 0, "warn": 0, "info": 0}
        for f in self.findings:
            counts[f.severity] = counts.get(f.severity, 0) + 1
        return counts


# ──────────────────────────────────────────────────────────────
# Heuristic helpers
# ──────────────────────────────────────────────────────────────

_FRONTMATTER_RE = re.compile(r'^---\n(.*?)\n---\n', re.DOTALL)
_MARKDOWN_IMAGE = re.compile(r'!\[.*?\]\(.*?\)')
_SKILL_MD_GENERIC_PHRASES = [
    "this skill helps", "this skill provides",
    "use this to", "general-purpose",
]


def _line_suppresses_audit(line: str) -> bool:
    """Respect inline suppression markers.

    Lines inside markdown blockquotes (> ...) are treated as quoted examples.
    Lines with an explicit `<!-- noqa: audit -->` or `<!-- audit: ignore -->` comment
    are also skipped.
    """
    stripped = line.lstrip()
    if stripped.startswith(">"):
        return True
    if "<!-- noqa: audit -->" in line or "<!-- audit: ignore -->" in line:
        return True
    return False


def _parse_frontmatter(text: str) -> dict[str, str] | None:
    m = _FRONTMATTER_RE.match(text)
    if not m:
        return None
    fields: dict[str, str] = {}
    key = None
    buf: list[str] = []
    for line in m.group(1).splitlines():
        if line and not line.startswith(" ") and ":" in line:
            if key is not None:
                fields[key] = "\n".join(buf).strip()
            key, _, rest = line.partition(":")
            key = key.strip()
            buf = [rest.strip()]
        else:
            buf.append(line)
    if key is not None:
        fields[key] = "\n".join(buf).strip()
    return fields


def _check_frontmatter(report: AuditReport, skill_md: Path) -> None:
    text = skill_md.read_text()
    fm = _parse_frontmatter(text)
    if fm is None:
        report.add("flag", "frontmatter", str(skill_md), 1,
                   "Missing YAML frontmatter (---...---)",
                   "Add `---\\nname: <kebab-case>\\ndescription: <pushy description>\\n---` at top of SKILL.md")
        return

    if "name" not in fm or not fm["name"]:
        report.add("flag", "frontmatter", str(skill_md), None,
                   "Missing required `name` field")
    elif not re.match(r"^[a-z0-9-]+$", fm["name"]):
        report.add("warn", "frontmatter", str(skill_md), None,
                   f"`name: {fm['name']}` is not kebab-case",
                   "Use lowercase letters, digits, and hyphens only")

    if "description" not in fm or not fm["description"]:
        report.add("flag", "frontmatter", str(skill_md), None,
                   "Missing required `description` field",
                   "Descriptions drive skill triggering — write a specific, pushy one")
        return

    desc = fm["description"]
    if len(desc) < 60:
        report.add("warn", "description", str(skill_md), None,
                   f"Description is {len(desc)} chars — probably too short to trigger well",
                   "Aim for 150-400 chars. Include trigger words and NOT-for cases")
    if len(desc) > 1000:
        report.add("warn", "description", str(skill_md), None,
                   f"Description is {len(desc)} chars — may be too long for efficient scanning",
                   "Compress. Move detail into SKILL.md body")

    pushy_signals = ["whenever", "use this", "use when", "make sure", "always"]
    if not any(s in desc.lower() for s in pushy_signals):
        report.add("info", "description", str(skill_md), None,
                   "Description lacks 'pushy' trigger signals (whenever/use when/make sure/always)",
                   "See references/description-tuning.md — Claude undertriggers skills by default")


def _check_suspicious_numbers(report: AuditReport, path: Path) -> None:
    """Round prices, fabricated-looking metrics."""
    text = path.read_text(errors="replace")
    lines = text.splitlines()
    for i, line in enumerate(lines, 1):
        if _line_suppresses_audit(line):
            continue

        # Context gate: if the line (or adjacent lines) cites a per-second rate,
        # a round per-hour number is probably derived arithmetic, not a hallucination.
        context_window = "\n".join(lines[max(0, i - 3): i + 2])
        has_per_second_context = bool(re.search(r'\$0\.\d{4,}/sec', context_window))

        for m in re.finditer(r'\$(\d+)\.(\d{2})/(hr|hour|sec|second|mo|month)', line):
            dollars, cents, unit = m.groups()
            # .00 / .50 prices are suspicious (hallucinated "plausible" values)
            # EXCEPT when accompanied by a per-second rate in the same region — then it's
            # derived and legit.
            if cents in ("00", "50") and int(dollars) > 1 and unit in ("hr", "hour"):
                if has_per_second_context:
                    continue  # derived from per-sec rate, not a hallucination signal
                report.add("warn", "suspicious-numbers", str(path), i,
                           f"Suspiciously round price: ${dollars}.{cents} "
                           f"(real GPU/API pricing rarely ends in .00 or .50)",
                           "Verify against the provider's current pricing page")

        # Narrow list of historically-observed hallucinated rates seen in actual LLM drafts.
        # Only include prices we have direct evidence were wrong. Don't add round numbers
        # speculatively — that's a false-positive generator.
        known_hallucinated = {
            "$3.50/hr": "H200 was hallucinated at $3.50; actual rate ~$4.54",
        }
        for bad, note in known_hallucinated.items():
            if bad in line and not has_per_second_context:
                report.add("flag", "suspicious-numbers", str(path), i,
                           f"Known-hallucinated GPU price: {bad} ({note})",
                           "Check modal.com/pricing or the provider's actual rate")


def _check_llm_slop_attributions(report: AuditReport, path: Path) -> None:
    text = path.read_text(errors="replace")
    patterns = [
        (r"Generated by (Claude|ChatGPT|GPT-\d|Assistant|AI)\b", "Remove the attribution footer"),
        (r"(?i)^(generated|produced|authored|created) by [A-Z][a-zA-Z-]+ Agent\b", "Generic 'Agent' attribution is a slop signal"),
        (r"(?i)this was generated by", "Remove the 'this was generated' attribution"),
        (r"(?i)as an AI (language )?model", "Remove the AI-model self-reference"),
    ]
    for i, line in enumerate(text.splitlines(), 1):
        if _line_suppresses_audit(line):
            continue
        for pat, suggestion in patterns:
            if re.search(pat, line):
                report.add("flag", "slop-attribution", str(path), i,
                           f"LLM-slop attribution detected: {line.strip()[:80]}",
                           suggestion)


def _check_stale_verified_markers(report: AuditReport, path: Path) -> None:
    text = path.read_text(errors="replace")
    for i, line in enumerate(text.splitlines(), 1):
        if _line_suppresses_audit(line):
            continue
        # Match "Last verified: April 2026" or "Verified: 2026-04-16"
        m = re.search(r'(?i)(?:last )?verified[:\s]+([A-Z][a-z]+ \d{4}|\d{4}-\d{2}-\d{2})', line)
        if not m:
            continue
        try:
            date_str = m.group(1)
            if "-" in date_str:
                d = datetime.strptime(date_str, "%Y-%m-%d").date()
            else:
                d = datetime.strptime(date_str, "%B %Y").date()
        except ValueError:
            continue
        age = date.today() - d
        if age > timedelta(days=90):
            report.add("warn", "staleness", str(path), i,
                       f"'Verified' marker is {age.days} days old: {date_str}",
                       "Re-verify the claims in this doc against upstream source, "
                       "then bump the date or add an ERRATA entry")


def _check_scripts(report: AuditReport, script: Path) -> None:
    """Parse Python scripts, check for __main__ guard and docstring."""
    try:
        tree = ast.parse(script.read_text())
    except SyntaxError as e:
        report.add("flag", "script-syntax", str(script), e.lineno,
                   f"Script does not parse: {e.msg}",
                   "Fix the syntax error before packaging")
        return

    # Top-level docstring
    module_doc = ast.get_docstring(tree)
    if not module_doc:
        report.add("info", "script-doc", str(script), 1,
                   "Script missing module-level docstring",
                   "Add a triple-quoted string at the top explaining purpose + usage")

    # __main__ guard for scripts named like CLIs
    has_main_guard = any(
        isinstance(node, ast.If) and
        isinstance(node.test, ast.Compare) and
        isinstance(node.test.left, ast.Name) and
        node.test.left.id == "__name__"
        for node in tree.body
    )

    # Recognize framework-specific entry decorators that make `__main__` guard redundant.
    # Modal: @app.local_entrypoint(), @app.function() as entry
    # Click / Typer: functions decorated with @click.command, @app.command
    # Flask/FastAPI: typically imported by a WSGI server, no main guard expected
    def _has_framework_entry(tree: ast.Module) -> bool:
        framework_decorators = {
            "local_entrypoint",  # Modal
            "command",           # click, typer
            "callback",          # typer
        }
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                for dec in node.decorator_list:
                    # @foo.bar() or @foo.bar
                    target = dec.func if isinstance(dec, ast.Call) else dec
                    if isinstance(target, ast.Attribute) and target.attr in framework_decorators:
                        return True
                    if isinstance(target, ast.Name) and target.id in framework_decorators:
                        return True
        return False

    has_framework_entry = _has_framework_entry(tree)

    if not has_main_guard and not has_framework_entry and any(
        isinstance(n, ast.FunctionDef) and n.name == "main" for n in tree.body
    ):
        report.add("info", "script-main", str(script), None,
                   "Has a `main()` function but no `if __name__ == '__main__'` guard",
                   "Add `if __name__ == '__main__': sys.exit(main())` so the script is importable")


def _check_tier3_shape(report: AuditReport, skill_root: Path) -> None:
    """A skill with docs/ or sub-skill directories should have ERRATA.md and a verification playbook."""
    has_docs = (skill_root / "docs").is_dir()
    has_subskills = any(
        (child / "SKILL.md").exists()
        for child in skill_root.iterdir()
        if child.is_dir() and child.name not in ("docs", "scripts", "references", "templates", "examples", "configs")
    )
    if not (has_docs or has_subskills):
        return
    if not (skill_root / "ERRATA.md").exists():
        report.add("warn", "tier3-shape", str(skill_root), None,
                   "Looks like a Tier 3 skill (has docs/ or sub-skills) but no ERRATA.md",
                   "Add an ERRATA.md to track drift; see skill-forge/templates/ERRATA.md.template")
    playbook = skill_root / "docs" / "00-verification-playbook.md"
    if has_docs and not playbook.exists():
        report.add("info", "tier3-shape", str(skill_root), None,
                   "Tier 3 skill without docs/00-verification-playbook.md",
                   "Add one so the next agent can audit your skill without re-deriving the method")


def _check_fabricated_identifiers(report: AuditReport, path: Path) -> None:
    """Very heuristic: flag function/class names that look like camelCase LLM guesses.
    This can't definitively prove a name is fabricated — only a source-check can.
    The goal is to remind the agent to verify, not to be a correctness oracle."""
    if not path.suffix == ".md":
        return
    text = path.read_text(errors="replace")
    # Look for Python-ish identifiers inside backticks that contain multiple capitalized words
    # and aren't common stdlib/well-known names — these are the shape of hallucinated APIs.
    known_good = {
        "HttpRequest", "HttpResponse", "BaseModel", "HuggingFace",
        "JsonResponse", "FastAPI", "OpenAI", "PyTorch",
    }
    for i, line in enumerate(text.splitlines(), 1):
        for m in re.finditer(r'`([A-Z][a-z]+[A-Z][a-z]+(?:[A-Z][a-z]+)+)`', line):
            ident = m.group(1)
            if ident in known_good:
                continue
            # Don't flag every camelCase — just in files that claim to document an API.
            # Heuristic: if the file has "reference" or "api" in the name, inspect more closely.
            if re.search(r'(reference|api|notes)', str(path).lower()):
                report.add("info", "verify-identifier", str(path), i,
                           f"CamelCase identifier `{ident}` — verify it exists in upstream source",
                           f"Check with: python scripts/gh_research.py find <owner>/<repo> '{ident}'")


# ──────────────────────────────────────────────────────────────
# Main audit
# ──────────────────────────────────────────────────────────────

def audit(skill_path: Path) -> AuditReport:
    report = AuditReport(skill_path=str(skill_path))

    skill_md = skill_path / "SKILL.md"
    if not skill_md.exists():
        report.add("flag", "structure", str(skill_path), None,
                   "No SKILL.md found at skill root",
                   "Every skill must have a top-level SKILL.md")
        return report

    _check_frontmatter(report, skill_md)

    for md in skill_path.rglob("*.md"):
        _check_suspicious_numbers(report, md)
        _check_llm_slop_attributions(report, md)
        _check_stale_verified_markers(report, md)
        _check_fabricated_identifiers(report, md)

    for py in skill_path.rglob("*.py"):
        if "__pycache__" in str(py):
            continue
        _check_scripts(report, py)

    _check_tier3_shape(report, skill_path)

    return report


def _print_report(report: AuditReport) -> None:
    counts = report.by_severity()
    print(f"\nAudit of {report.skill_path}")
    print(f"  {counts['flag']} flag · {counts['warn']} warn · {counts['info']} info")
    print()

    severity_order = {"flag": 0, "warn": 1, "info": 2}
    severity_symbol = {"flag": "✗", "warn": "!", "info": "·"}
    sorted_findings = sorted(
        report.findings,
        key=lambda f: (severity_order[f.severity], f.file, f.line or 0),
    )
    for f in sorted_findings:
        loc = f.file + (f":{f.line}" if f.line else "")
        print(f"  {severity_symbol[f.severity]} [{f.category}] {loc}")
        print(f"      {f.message}")
        if f.suggestion:
            print(f"      → {f.suggestion}")
        print()

    if not report.findings:
        print("  ✓ No issues found.")


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description="Anti-slop audit for a draft Claude skill.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    p.add_argument("skill_path", help="Path to the skill directory to audit")
    p.add_argument("--json", action="store_true", help="Emit JSON instead of prose")

    args = p.parse_args(argv)
    skill_path = Path(args.skill_path).resolve()
    if not skill_path.exists():
        print(f"ERROR: {skill_path} does not exist", file=sys.stderr)
        return 2

    report = audit(skill_path)

    if args.json:
        print(json.dumps({
            "skill_path": report.skill_path,
            "counts": report.by_severity(),
            "findings": [asdict(f) for f in report.findings],
        }, indent=2))
    else:
        _print_report(report)

    # Exit code: 0 if only info, 1 if warnings, 2 if flags
    counts = report.by_severity()
    if counts["flag"]:
        return 2
    if counts["warn"]:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
